# Generated by Django 5.1.7 on 2025-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameIntelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField()),
                ('open_cards', models.JSONField(default=list)),
                ('vira', models.JSONField()),
                ('opponent_card', models.JSONField(blank=True, null=True)),
                ('round_results', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('hand_points', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
